download_deps:
  image: python:3.6
  stage: download_deps
  before_script:
    - pip install virtualenv
    - virtualenv env
    - . ./env/bin/activate
  script:
    - pip install -r dev.requirements.txt
  artifacts:
    paths:
      - "env"
    expire_in: 1 hour
  tags:
    - docker

test:
  image: python:3.6
  stage: test
  dependencies:
    - download_deps
  before_script:
    - . ./env/bin/activate
  script:
    - py.test --cov-report term --cov=illuin_config ./tests
  coverage: '/\d+\%\s*$/'
  tags:
    - docker

lint:
  image: python:3.6
  stage: test
  dependencies:
    - download_deps
  before_script:
    - . ./env/bin/activate
  script:
    - pylint --load-plugins pylint_quotes illuin_config
    - pylint --load-plugins pylint_quotes tests --disable=protected-access,too-many-instance-attributes,no-self-use
  tags:
    - docker

deploy:
  image: python:3.6
  stage: deploy
  dependencies:
    - download_deps
  before_script:
    - |
      cat > ~/.pypirc << EOF
      [distutils]
      index-servers =
        pypi

      [pypi]
      repository: https://www.python.org/pypi
      username: ${PYPI_PUSH_USERNAME}
      password: ${PYPI_PUSH_PASSWORD}
      EOF
    - . ./env/bin/activate
  script:
    - sed -i "s#version=\"DEV\",#version=\"${CI_COMMIT_TAG}\",#g" setup.py
    - python setup.py sdist bdist_wheel
    - twine upload -r pypi dist/illuin[-_]config-${CI_COMMIT_TAG}*
  tags:
    - docker
  only:
    - tags

stages:
  - download_deps
  - test
  - deploy
